name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create version file
      run: mkdir /home/runner/work/PojavLauncher/PojavLauncher/jre_lwjgl3glfw/build/ && touch /home/runner/work/PojavLauncher/PojavLauncher/jre_lwjgl3glfw/build/version
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew && chmod +x scripts/languagelist_updater.sh
    - name: Build
      run: ./gradlew :jre_lwjgl3glfw:build && ./gradlew :app_pojavlauncher:assembleDebug
