name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle
      - name: Create version file
        run: mkdir /home/runner/work/PojavLauncher/PojavLauncher/jre_lwjgl3glfw/build/ && touch /home/runner/work/PojavLauncher/PojavLauncher/jre_lwjgl3glfw/build/version

      - name: Grant execute permission for gradlew
        run: chmod +x scripts/languagelist_updater.sh && bash scripts/languagelist_updater.sh
      - name: Build with Gradle
         run: ./gradlew :jre_lwjgl3glfw:build && ./gradlew  assembleDebug
